name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Maven-java-Build:

    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.Install_git.outputs.test }}

    strategy :
      matrix :
        version : [1.8, 1.7]
    
    steps:
    - name : Giving permission to our Repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.version }}

    - name: Install_git
      run: |
        sudo apt-get install -y git 
        sudo mkdir client
        echo "::set-output name=test::git --version"

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
      working-directory: client

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Storing artifacts
      uses: actions/upload-artifact@v3
      with:
        name: myArtifacts
        path: client
        retention-days: 1
        
  Building-and-Pushing-an-Docker-Image:
  
      runs-on : ubuntu-latest
      defaults:
       run:
        working-directory: client
      steps :
        - name: docker-upload
          uses: mr-smithers-excellent/docker-build-push@v4
          with:
           image: raji2306/demo-app
           registry: docker.io
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
        - name: echo_da
          run: echo ${{needs.Maven-java-Build.outputs.output1}} 
